<a href="https://colab.research.google.com/github/RoshitRana/Worksheet0/blob/main/workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Qno.1

In [ ]:
import numpy as np


empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)


ones_array = np.ones((4, 2))
print("\nOnes Array (4x2):\n", ones_array)

shape = (3, 3)  # Example shape
fill_value = 7
full_array = np.full(shape, fill_value)
print("\nFull Array (3x3 filled with 7):\n", full_array)

existing_array = np.array([[1, 2], [3, 4]])  # Example array
zeros_like_array = np.zeros_like(existing_array)
print("\nZeros Like Array:\n", zeros_like_array)

ones_like_array = np.ones_like(existing_array)
print("\nOnes Like Array:\n", ones_like_array)


new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted Numpy Array from List:", numpy_array)


Empty Array (2x2):
 [[4.70054272e-310 0.00000000e+000]
 [6.93489444e-310 0.00000000e+000]]

Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0]
 [0 0]]

Ones Like Array:
 [[1 1]
 [1 1]]

Converted Numpy Array from List: [1 2 3 4]


qno.2


In [ ]:
import numpy as np

# Array from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

#  3x3 Matrix from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix_3x3)

# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

#  Random Array (30 elements) and Mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array (30 elements):\n", random_array)
print("Mean of the Array:", mean_value)

#  Random 10x10 Array and Min/Max Values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nRandom 10x10 Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# Zero Array of size 10 with 5th element replaced by 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("\nZero Array with 5th Element Replaced with 1:\n", zero_array)

#  Reverse an Array [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:", reversed_arr)

#  2D Array with 1 on Border and 0 Inside
border_ones = np.ones((5, 5))
border_ones[1:-1, 1:-1] = 0  # Set the inner elements to 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_ones)

#  8x8 Checkerboard Pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (30 elements):
 [0.1581352  0.70887883 0.16907499 0.01269859 0.09059679 0.70649944
 0.77838815 0.01583396 0.66795533 0.59225719 0.28464807 0.12407216
 0.99882796 0.05238798 0.71901215 0.33101425 0.19964666 0.06255589
 0.85774543 0.22895162 0.40148155 0.0278649  0.85573954 0.16578921
 0.63017201 0.47065809 0.20479951 0.08188974 0.98907275 0.51782417]
Mean of the Array: 0.4034824034500183

Random 10x10 Array:
 [[0.35630066 0.84421627 0.0942465  0.94097595 0.17112315 0.03207718
  0.22862444 0.01411104 0.56434536 0.48842242]
 [0.5279699  0.04222808 0.86632668 0.48014308 0.35907586 0.82596642
  0.27430705 0.21370396 0.15363091 0.04892128]
 [0.38313228 0.05132577 0.94850156 0.84629682 0.74300739 0.97719609
  0.40516422 0.73

Qno.3


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the two arrays
add_result = x + y
print("Addition of x and y:\n", add_result)

# Subtract the two arrays
subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

#  Multiply the array with any integer of your choice
multiply_result = x * 2
print("\nMultiplication of x with 2:\n", multiply_result)

# Find the square of each element of the array
square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

#  Find the dot product between v and w, x and v, x and y
dot_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("\nDot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("\nDot product of x and y:\n", dot_xy)

# Concatenate x and y along rows and concatenate v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_rows)

v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw_cols = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("\nConcatenate v and w along columns:\n", concat_vw_cols)

# Concatenate x and v (Explain the error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v along rows:\n", concat_xv)
except Exception as e:
    print("\nError when trying to concatenate x and v along rows:", e)

try:
    concat_xv_cols = np.concatenate((x, v), axis=1)
    print("\nConcatenate x and v along columns:\n", concat_xv_cols)
except Exception as e:
    print("\nError when trying to concatenate x and v along columns:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error when trying to concatenate x and v along rows: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Error when trying to concatenate x and v along columns: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Qno.4

In [ ]:
import numpy as np

# Arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.eye(2)  # 2x2 identity matrix
result = np.dot(A, A_inv)
print("A * A^-1:\n", result)
print("Identity Matrix I:\n", I)

#  Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

#  Prove (AB)^T = B^T * A^T
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)

#  Solve the system of linear equations using the Inverse Method

# Coefficient matrix A and constants vector B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using the inverse method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution (x, y, z) using Inverse Method:\n", X)

# Solve the system of linear equations using np.linalg.inv directly
X_direct = np.linalg.inv(A).dot(B)
print("\nDirect Solution using np.linalg.inv:\n", X_direct)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

Solution (x, y, z) using Inverse Method:
 [ 2.  1. -2.]

Direct Solution using np.linalg.inv:
 [ 2.  1. -2.]
